version: '3.8'

services:
  db:
    restart: always
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev

  django:
    restart: always
    volumes:
      - ./media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    build: ./
    env_file:
      - ./.env.dev
    ports:
      - "8080:8000"
    depends_on:
      - db

volumes:
  postgres_data: null
