# Generated by Django 3.2.15 on 2023-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_auto_20230330_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Долгота'),
        ),
    ]
