# Generated by Django 3.2.15 on 2023-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230325_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_form',
            field=models.CharField(choices=[('not_set', 'Не выбран'), ('now', 'Сразу'), ('online', 'Электронно'), ('cash', 'Наличностью')], db_index=True, default='Не выбран', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
